### ISSUE TITLE
Syntax coloring inside html attribute templates

### ISSUE THREAD

**Issue by sergiucaraian** [mydesireiscoma/es6-string-html#12]
Hello

I'm using a html-generating template function, however the HTML attributes don't get syntax colored:

<img width="594" alt="s1" src="https://user-images.githubusercontent.com/7252396/44033070-ddeacf40-9f11-11e8-95d5-74f6e24f389d.PNG">

Ideally, they would look like this:

<img width="542" alt="s2" src="https://user-images.githubusercontent.com/7252396/44033087-ecac7fd8-9f11-11e8-8c7c-7ebd1be7f608.PNG">

When I place event listeners inline, my library requires that they are surrounded by quotes ( ``onclick="${myFunc}"`` ),  just like other attributes, however other libraries may use the template literal directly ( ``onclick=${myFunc}`` ), like they do in React.

**Comment by mydesireiscoma** [comment]
Thankyou for the issue
I'll try to implement this feature

**Comment by oxygen** [comment]
Actually, I'd consider this a bug.

![image](https://user-images.githubusercontent.com/4642698/44238801-de493d00-a1be-11e8-898a-f90a6b77dd21.png)

**Comment by mydesireiscoma** [comment]
@sergiucaraian 
Will be fixed today/tomorrow

**Comment by mydesireiscoma** [comment]
@sergiucaraian 

Fixed
Package in the marketplace is updated
Feel free to close the issue if the plugin works as you expected

Thankyou

**Comment by oxygen** [comment]
@mydesireiscoma 
The bug is still there for /*sql*/.

Can you fix that too?
10q

**Comment by mydesireiscoma** [comment]
Sure
